version: '3.8'

services:
    mysql:
      image: mysql:latest
      container_name: mysql_database
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: knex_test@root
        MYSQL_DATABASE: knex_test
        MYSQL_USER: user
        MYSQL_PASSWORD: knex_test@user
        MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
    dev:
      build: .
      command: npm start
      volumes:
        - .:/usr/app/
        - /usr/app/node_modules
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: user
        MYSQL_PASSWORD: knex_test@user
        MYSQL_DATABASE: knex_test
volumes:
  mysql_data:
    driver: local